### ISSUE TITLE
Standardise with W3C

### ISSUE THREAD

**Issue by cvan** [MozVR/webvr-spec#16]

**Comment by toji** [comment]
Speaking to Alex Russell and Chris Wilson at Google, it sounds like a good route to go may be setting up a W3C community group. It's supposed to be a pretty lightweight process that provides some basic IP protections. Worth looking into IMO.

**Comment by cvan** [comment]
Not sure this is the right place, but I proposed a Community Group here: https://www.w3.org/community/groups/proposed/#webvr

We're talking to David Baron here at Mozilla to see if there's anything special we should do too.

**Comment by toji** [comment]
Looks like the right place to me! Registered my support for the API on there.

**Comment by cvan** [comment]
[We have a community group!](https://www.w3.org/community/webvr/)

**Comment by cvan** [comment]
@toji: could you join the community group as a participant?

**Comment by dmarcos** [comment]
@toji To move things forward you have to join the community group as a participant. Basically you have to show up in this page: https://www.w3.org/2000/09/dbwg/details?group=87846&public=1&order=org
Someone with w3c super powers have to manually accept you as participant. Alex Russell might be able to do it for you.

**Comment by toji** [comment]
I'm working on joining, there's some (minor) hoops to jump through on the Google side. I'll let you know when I know more.

**Comment by LaszloGombos** [comment]
Mike Blix and me are working on joining the CG as well from Samsung.

**Comment by toji** [comment]
Hoops have been jumped! I'm now a participant in the group. :D

**Comment by dmarcos** [comment]
@toji Welcome

**Comment by louaybassbouss** [comment]
I will also join the CG from [Fraunhofer FOKUS](https://www.fokus.fraunhofer.de/en)

**Comment by cvan** [comment]
Spec repo moved to https://github.com/w3c/webvr

**Comment by cvan** [comment]
**_Moved to w3c/webvr#24_**
