### ISSUE TITLE
Clarify: Can the main monitor be a VR Display?

### ISSUE THREAD

**Issue by brianchirls** [MozVR/webvr-spec#21]
For example, if it's a 3D TV? Have any of the browser vendors discussed implementing something like that?

**Comment by dmarcos** [comment]
a 3D tv doesn't use the same method to render stereo than vr headset (side by side left/right eye + distortion) I don't know how a browser would present content on a 3d tv

**Comment by dmarcos** [comment]
there's probably different methods depending on the display vendor

**Comment by toji** [comment]
To present to a 3D TV you would probably need to use something like a Quadbuffer stereo WebGL extension. There's definitely a path for it to make it into the browser, but I don't think WebVR is the right place for it. (I think one of the defining aspects of a "VRDisplay" is that it's responsive to view movement somehow. 3D TV doesn't really fit that bill.)
