### ISSUE TITLE
ambiguity on number of VRLayers

### ISSUE THREAD

**Issue by andreasplesch** [MozVR/webvr-spec#23]
While the plural in getLayers as well as the word layer itself indicate that more than one Layer can be presented, presentRequest and the wording of the explanation of VRLayer indicate that only a single Layer can be presented.

This ambiguity can lead to confusion and should be removed.

Although implementations currently only allow for a single Layer, the spec. may be more demanding and allow multiple Layers.

**Comment by toji** [comment]
Sorry, this is clarified in the most recent version of the spec, but I only just now realized that we hadn't updated the live page. I've done so now, and you can read the explanation of this behavior at https://mozvr.github.io/webvr-spec/#dom-vrdisplay-getlayers

**Comment by andreasplesch** [comment]
Thanks. The wording is very clear now.
