### ISSUE TITLE
rename VRLayer

### ISSUE THREAD

**Issue by andreasplesch** [MozVR/webvr-spec#24]
Layering requires multiple layers. However, currently only a single VRLayer can be presented by the display.
Therefore VRSource would be a better fit as a suggestion. There are probably better names to be discovered as well.

**Comment by toji** [comment]
As mentioned in #23 I've updated the live version of the spec with some verbiage that explains this (admittedly awkward) phrasing. The short version is that we're intentionally leaving room for future expansion.

**Comment by andreasplesch** [comment]
While the spec. now has been clarified, it may be wise to use interface names which reflect its actual usage most accurately and not to try to anticipate what the future may or may not bring. Future revisions may deprecate but still allow older naming schemes for smoother transitions.
Why carry around an awkward name for a potentially long time ? It is still early and making such changes will become more difficult.
