### ISSUE TITLE
Need a way to determine whether rendering is falling below target frame rate

### ISSUE THREAD

**Issue by brianchirls** [MozVR/webvr-spec#29]
I've been thinking about the possibility of adapting render quality to achieve the optimal frame rate, as described in [this article](http://arstechnica.com/gaming/2016/03/how-valve-got-passable-vr-running-on-a-four-year-old-graphics-card/). The article mentions things like adjusting the pre-distortion render buffer scale, adjusting anti-aliasing detail and some more complicated ideas. I was also thinking about adjusting the far end of z-clipping (with some fog) as it's appropriate for content, levels of detail, etc.

In order to do this, we need to know how well we're doing at meeting the target frame rate. The simplest way I can think of doing this is to report the frame rate of the VRDisplay device. Presumably, this would be fixed for now, but I suppose not necessarily forever. I suppose there are some arguments to be made against providing this information, but since there are annoying but feasible ways to figure it out, we may as well provide it easily and correctly.

One way that this falls short, however, is that if you _are_ rendering at the optimal frame rate, there isn't really a good way to know if you've got a little extra time so you can bump the quality up or run some other tasks. You'd have to try raising the quality and then waiting to see if that drops the frame rate, which is certainly not ideal. If anybody has any ideas about that, I'd love to hear them.

cc: @toji, per our chat in webvr slack

**Comment by mkeblx** [comment]
API could provide but timing of two rAF will tell you the frame rate pretty simply without any rendering required, etc. Say currently running at consistent frame rate. (frametime - rendertime) / frametime ratio <1 which can have a goal with a buffer of leaving x% of frametime.

You shouldn't have to do anything that would cause missing framerate assuming can move in suitably small increments to test is still under budget after increase. This seems like a more generic problem of performance scaling like would have targeting mobile + desktop.

**Comment by cvan** [comment]
**_Moved to w3c/webvr#37_**
