### ISSUE TITLE
The right way to enter VR mode

### ISSUE THREAD

**Issue by borismus** [MozVR/webvr-spec#3]
The current approach of going into VR mode via `requestFullScreen({vrDisplay: hmd})` seems a little bit limiting. Why should full-screen be associated with VR? Does it still make sense for direct-to-rift mode, where only the rift display should be affected? How about for Cardboard-style uses?

What if we had something like `hmd.startVR()` instead?

/cc: @dmarcos

**Comment by toji** [comment]
I like to think of the current syntax as implying "I want you to display this content fullscreen on device X". The "VR" part of it may be overtly specific, but suits the immediate need.

Thus far, we haven't seen any devices where it's meaningful to render anything other than a fullscreen view for the purposes of VR. Beyond that, however, it serves as a useful base for progressive enahancement that does _almost_ the right thing in several situations. For example: On Android even if you have no support for HMD distortion or anything like that you can render a split screen canvas fullscreen and it looks acceptable in a Cardboard harness. If we then add distortion support the same command will now get automatically "upgraded" to a more correct version while still being backwards compatible with other/older browsers. Same goes for something like the Oculus Rift. Even if "VR fullscreen" isn't natively supported you could at least mirror displays and use fullscreen to see an image that swims around the edges. (Better than nothing!) That's the kind of evolutionary track that the web thrives on.

**Comment by borismus** [comment]
OK, any reason why the vrDevice argument to requestFullscreen isn't
captured in the spec? I'd like to polyfill this behavior too.

**Comment by jbaicoianu** [comment]
One important question this raises is how screen duplication would work with this system.  Currently in FF Nightly with Oculus Rift 0.7.0 runtime, upon entering fullscreen with a vrDisplay the canvas is moved to the Rift display and what's left on the monitor is just whatever was behind the canvas.

Would it be possible to send an option to requestFullScreen() to do screen mirroring itself?  I believe the Oculus SDK has a way to do this in an efficient way with the new direct driver mode.

Barring that, there's the option of duplicating the canvas element's content at the app level, but probably at the price of performance.

**Comment by toji** [comment]
Issue is no longer relevant with upcoming API changes. Closing.
