### ISSUE TITLE
hasOrientation (& hasPosition) flags

### ISSUE THREAD

**Issue by mkeblx** [MozVR/webvr-spec#30]
What is the use case of these `VRDisplayCapabilities` flags on `VRDisplay`? Especially `hasOrientation` as hard to imagine HMD not having orientation tracking.

Also note specifically renamed from `VRDevice` to `VRDisplay` to focus spec on covering use case of HMDs (mainly) and not generic tracked VR devices.

Additionally can be figured out by null or not state of orientation and position data.

**Comment by toji** [comment]
The difference between a `null` position and `hasPosition`has been explained by @kearwood in the past with the "Cat scenario". If a cat walks in front of my tracking camera/laser box and tracking drops, it may appear that the device has no position tracking at all if all you are looking at is the pose data. `hasPosition == true && pose.position == null` says "I have the ability to track your position, I'm just not able to do it right now."

**Comment by cvan** [comment]
**_Moved to w3c/webvr#38_**
