### ISSUE TITLE
Spec Gamepad property changes

### ISSUE THREAD

**Issue by cvan** [MozVR/webvr-spec#31]
In @toji's latest Chromium builds (see [patch diff](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr_1%5E%21/)), there's a property `pose` now exposed on the `Gamepad` objects. (See [example of usage](https://github.com/toji/webvr-samples/blob/c8a4392/XX-vr-controllers.html#L232-L276).)

We should document the [WebIDL changes in the WebVR spec here](https://w3c.github.io/gamepad/#gamepadevent-interface).

We ought to also file an issue against [the Gamepad API spec](https://github.com/w3c/gamepad).

**Comment by toji** [comment]
FYI: I've proposed this and a couple other changes on the mailing list. http://lists.w3.org/Archives/Public/public-webapps/2016AprJun/0052.html

**Comment by cvan** [comment]
**_Moved to w3c/webvr#39_**
